### ISSUE TITLE
Trying to build gt-ac5300

### ISSUE THREAD

**Issue by stevef9432203** [blackfuel/asuswrt-gt-ac5300#1]
Can't  actually find the correct "tools/brcm" directory 
ANY SUGGESTIONS

**Comment by blackfuel** [comment]
First, download the official GPL source code from ASUS and use it instead of this Github project.  This Github project is intended for full-text search of the source code only.
https://www.asus.com/us/Networking/ROG-Rapture-GT-AC5300/HelpDesk_Download/

I think these are the ARMv8 toolchains.  There's two toolchains because ARMv8 supports both aarch64 and aarch32 modes.  The Asuswrt Linux kernel is compiled as aarch64, and the userspace programs are compiled as aarch32.
https://github.com/blackfuel/asuswrt-gt-ac5300/tree/master/release/src-rt-5.02hnd/bcmdrivers/broadcom/net/wl/impl51/main/src/toolchains
